import FooterCom from "@/components/FooterCom";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider/AuthProvider";
import { dbConnect } from "@/services/dbConnect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Khana-Home",
  description: "Generated by a Khana Khazana project",
};

export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <AuthProvider>
            <Navbar />
            <main>{children}</main>
            <FooterCom />
          </AuthProvider>
        </>
      </body>
    </html>
  );
}
